name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
